package ninjadeps_test

import (
	"path/filepath"
	"slices"
	"testing"

	"github.com/yerden/herbarium/internal/ninjadeps"
)

// The fixture builddir has been generated by Meson/ninja with a real
// build. Its .ninja_deps encodes six .o files, each with its transitive
// header set. This test walks the shape once and locks in the invariants
// the parser must preserve: correct object recognition, path fidelity
// (no leftover NUL padding, correct forward slashes), and the "later
// deps record wins" rule (implicitly — no output should appear twice in
// the returned map).
func TestReadFixture(t *testing.T) {
	log, err := ninjadeps.ReadForBuildDir(filepath.Join("..", "..", "testdata", "fixture", "builddir"))
	if err != nil {
		t.Fatalf("ReadForBuildDir: %v", err)
	}
	if log == nil {
		t.Fatal("ReadForBuildDir: nil log (fixture builddir missing .ninja_deps?)")
	}
	if log.Version != ninjadeps.SupportedVersion {
		t.Errorf("version = %d, want %d", log.Version, ninjadeps.SupportedVersion)
	}

	// Every .o under the fixture builddir should have an entry.
	wantOuts := []string{
		"lib/libshared.a.p/dispatch_impls.c.o",
		"lib/libshared.a.p/weak_impl.c.o",
		"lib/libshared.a.p/shared_utils.c.o",
		"app1/app1.p/strong_override.c.o",
		"app1/app1.p/main.c.o",
		"app2/app2.p/main.c.o",
	}
	for _, out := range wantOuts {
		deps, ok := log.DepsFor(out)
		if !ok {
			t.Errorf("no deps for %q", out)
			continue
		}
		if len(deps) == 0 {
			t.Errorf("empty deps for %q", out)
		}
		// The first dep is always the .c source itself (ninja preserves
		// GCC's -MMD output order, which lists the primary source first).
		if len(deps) > 0 && !hasSuffix(deps[0], ".c") {
			t.Errorf("%s: first dep %q is not the .c source", out, deps[0])
		}
		for _, d := range deps {
			if d == "" {
				t.Errorf("%s: empty dep path", out)
			}
			// Padding NULs must be stripped.
			if hasNul(d) {
				t.Errorf("%s: dep %q retains NUL bytes", out, d)
			}
		}
	}

	// dispatch_impls.c.o must have include/dispatch.h in its dep set —
	// that's the header it #includes.
	deps, _ := log.DepsFor("lib/libshared.a.p/dispatch_impls.c.o")
	if !slices.Contains(deps, "../include/dispatch.h") {
		t.Errorf("dispatch_impls.c.o deps missing ../include/dispatch.h; got %v", deps)
	}
}

func hasSuffix(s, suf string) bool {
	if len(s) < len(suf) {
		return false
	}
	return s[len(s)-len(suf):] == suf
}

func hasNul(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] == 0 {
			return true
		}
	}
	return false
}

